// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CurrentWeather struct {
	ID        string  `json:"id"`
	Location  string  `json:"location"`
	Condition string  `json:"condition"`
	Zipcode   string  `json:"zipcode"`
	Temp      float64 `json:"temp"`
	Code      string  `json:"code"`
}
